import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: "cover",
  },
  form: {
    margin: 30,
    marginTop: 60,
  },
  label: {
    fontSize: 18,
    marginBottom: 30,
    textAlign: "center",
    color: "white",
  },

  NoteLabel: {
    fontSize: 18,
    padding: 10,
    textAlign: "center",
    color: "white",
  },
  watchLocationText: {
    fontSize: 18,
    marginBottom: 10,
    marginTop: 10,
    textAlign: "center",
    color: "white",
  },
  namePass: {
    fontSize: 25,
    marginBottom: 20,
    marginTop: 10,
    textAlign: "center",
    color: "white",
  },
  dbOutput: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "left",
    color: "white",
  },
  cameraText: {
    fontSize: 18,
    marginBottom: 10,
    textAlign: "center",
    color: "white",
  },
  textValue: {
    fontSize: 18,
    textAlign: "center",
    color: "white",
    marginBottom: 10,
  },
  header: {
    fontSize: 30,
    marginBottom: 30,
    textAlign: "center",
  },
  headerText: {
    fontSize: 28,
    marginBottom: 30,
    textAlign: "center",
    fontWeight: "bold",
    color: "white",
  },
  textInput: {
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
    marginTop: 20,
    marginBottom: 15,
    paddingVertical: 4,
    paddingHorizontal: 2,
    textAlignVertical: "top",
    color: "white",
  },
  watchLocation: {
    borderBottomColor: "blue",
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderTopColor: "blue",
  },
  buttonContainer: {
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
  },
  welcomeButtonContainer: {
    marginTop: 100,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },

  icon: {
    width: "40%",
  },
  iconContainer: {
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: "70%",
    marginLeft: "4%",
  },
  SmsEmailContainer: {
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: "70%",
    marginLeft: "15%",
  },
  WelcomeButton: {
    width: "45%",
    borderWidth: 1,
    borderColor: "white",
    //top: "25%",
  },
  WelcomeButtonFull: {
    width: "90%",
    borderWidth: 1,
    borderColor: "white",
    marginTop: 10,
    marginLeft: 20,
    //top: "25%",
  },
  SQLSaveButton: {
    width: "85%",
    borderWidth: 1,
    borderColor: "white",
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 10,
  },
  button: {
    width: "40%",
  },
  welcomeImage: {
    width: 100,
    height: 100,
  },
  welcomeImageContainer: {
    // flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },

  aboutContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    //backgroundColor: "#F5FCFF80",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  inputContainer: {
    flex: 1,
    //  marginTop: 50,
    backgroundColor: "rgba(0, 0, 0, 1)",
  },
  textModalButton: {
    backgroundColor: "#010125",
    borderRadius: 5,
    borderColor: "white",
    borderWidth: 1,
    padding: 10,
    margin: 15,
    // marginHorizontal: 20,
    marginTop: 10,
  },
  modalButton: {
    backgroundColor: "black",
    borderRadius: 5,
    borderColor: "blue",
    borderWidth: 1,
    padding: 10,
    marginHorizontal: 20,
    marginTop: 10,
  },

  modalButtonIcon: {
    backgroundColor: "black",
    borderRadius: 5,
    borderColor: "blue",
    borderWidth: 1,
    padding: 10,
    marginHorizontal: 20,
    marginTop: 10,
  },
  modalButtonText: {
    color: "white",
    textAlign: "center",
    marginLeft: 30,
    marginRight: 30,
  },
  inputTitle: {
    width: "90%",
    borderBottomColor: "#505089",
    borderBottomWidth: 2,
    padding: 10,
    marginBottom: 20,
    marginTop: 30,
    marginLeft: 20,
    fontSize: 30,
    color: "white",
  },
  registerInput: {
    width: "90%",
    borderBottomColor: "#505089",
    borderBottomWidth: 2,
    padding: 10,
    marginBottom: 20,
    marginTop: 30,
    marginLeft: 20,
    fontSize: 20,
    color: "white",
  },
  inputBody: {
    width: "90%",
    borderColor: "#2c2c52",
    borderWidth: 0.5,
    padding: 10,
    marginBottom: 10,
    marginLeft: 20,
    height: 350,
    color: "white",
    textAlignVertical: "top",
  },
  inputMessageBody: {
    width: "90%",
    borderColor: "#2c2c52",
    borderWidth: 0.5,
    padding: 10,
    marginBottom: 10,
    marginLeft: 20,
    height: 400,
    color: "white",
    textAlignVertical: "top",
  },
  mapStyle: {
    marginLeft: 30,
    borderColor: "#2c2c52",
    borderWidth: 1,
    marginRight: 30,
    marginBottom: 10,
  },
  json: {
    fontSize: 18,
    marginBottom: 10,
    color: "white",
  },
  modalView: {
    margin: 20,
    // backgroundColor: "#21215e90",
    backgroundColor: "#04244690",
    borderRadius: 5,
    padding: 60,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  listItem: {
    padding: 10,
    marginVertical: 10,
    backgroundColor: "black",
    borderColor: "white",
    borderWidth: 3,
  },
});
